{% set name = "prism_viewer" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - prism_viewer = prism_viewer.main:main

requirements:
  build:
    - python =3.8  
    - {{ compiler('cxx') }}
  host:
    - python =3.8  
    - pip
    - setuptools
    - numpy =1.22.4
    - swig
    - pythonocc-core =7.8.1  
  run:
    - python =3.8  
    - {{ pin_compatible('numpy') }}
    - pyqt
    - sqlite
    - occt =7.8.1 *novtk*  
    - six
    - svgwrite

test:
  imports:
    - prism_viewer
  requires:
    - pytest
  commands:
    - python -m pytest prism_viewer/tests/

about:
  home: "https://github.com/anuranjani23/fossee-3D-rectangular-prism-viewer.git"
  license: MIT
  summary: "A PyQt5 and PythonOCC-based 3D rectangular prism viewer application."

extra:
  recipe-maintainers:
    - anuranjani23
